In [13]:
from datasets import load_dataset

dataset = load_dataset("tatsu-lab/alpaca")
# alpaca because we want our model to learn how to ans correctly and its data size is also good
dataset

DatasetDict({
    train: Dataset({
        features: ['instruction', 'input', 'output', 'text'],
        num_rows: 52002
    })
})

In [14]:
import pandas as pd

df = dataset["train"].to_pandas()

df.head(10)

,instruction,input,output,text
0,Give three tips for staying healthy.,,1.Eat a balanced diet and make sure to include...,Below is an instruction that describes a task....
1,What are the three primary colors?,,"The three primary colors are red, blue, and ye...",Below is an instruction that describes a task....
2,Describe the structure of an atom.,,"An atom is made up of a nucleus, which contain...",Below is an instruction that describes a task....
3,How can we reduce air pollution?,,There are a number of ways to reduce air pollu...,Below is an instruction that describes a task....
4,Describe a time when you had to make a difficu...,,I had to make a difficult decision when I was ...,Below is an instruction that describes a task....
5,Identify the odd one out.,"Twitter, Instagram, Telegram",Telegram,"Below is an instruction that describes a task,..."
6,Explain why the following fraction is equivale...,4/16,The fraction 4/16 is equivalent to 1/4 because...,"Below is an instruction that describes a task,..."
7,Write a short story in third person narration ...,,John was at a crossroads in his life. He had j...,Below is an instruction that describes a task....
8,Render a 3D model of a house,,<nooutput> This type of instruction cannot be ...,Below is an instruction that describes a task....
9,Evaluate this sentence for spelling and gramma...,He finnished his meal and left the resturant,He finished his meal and left the restaurant.,"Below is an instruction that describes a task,..."

In [15]:
df.shape

(52002, 4)

In [16]:
df.columns

Index(['instruction', 'input', 'output', 'text'], dtype='str')

In [24]:
df.sample(5, random_state=42)[["instruction", "input", "output","text"]]

,instruction,input,output,text
38199,Describe the character of the protagonist in t...,Game of Thrones,The protagonist of Game of Thrones is the long...,"Below is an instruction that describes a task,..."
20985,Construct a poem that describes the beauty of ...,,"The setting sun paints a scene of beauty, \nA ...",Below is an instruction that describes a task....
13643,Describe the effects of exponential growth.,,Exponential growth is a phenomenon in which an...,Below is an instruction that describes a task....
11300,Imagine a future world where robots and humans...,,"In the future, robots and humans will exist to...",Below is an instruction that describes a task....
32153,Create a list of three benefits of cloud compu...,,"1. Cost savings, as most cloud computing servi...",Below is an instruction that describes a task....

In [18]:
df["input"].eq("").sum()

np.int64(31323)

In [25]:
df["instruction"].duplicated().sum()
# how many duplicates avilable

np.int64(0)

In [20]:
df["output"].str.len().describe()

count    52002.000000
mean       270.312334
std        275.025960
min          0.000000
25%         53.000000
50%        185.000000
75%        423.000000
max       4181.000000
Name: output, dtype: float64

In [21]:
# longest example 
df.loc[df["output"].str.len().nlargest(5).index, ["instruction", "output"]]

,instruction,output
6285,Generate a 10 annotated bibliography given the...,"1. Anderson, B. (2012). Climate Change and Hum..."
45289,Explain a common misconception about your topic.,A common misconception about AI augmentation i...
15102,Explain how the Gini index is calculated.,The Gini index is a measure of economic inequa...
15908,Write four articles on the topic of cryptocurr...,Article #1\nWhat Is Cryptocurrency?\n \nCrypto...
26999,Generate an essay of at least 500 words that a...,Artificial intelligence (AI) has been a hot to...

In [12]:
df[df["output"].str.strip().eq("")][["instruction", "input", "output"]]

,instruction,input,output
284,Standardize the following date to the ISO 8601...,"July 26th, 2021",
1223,Create an illustration for the following text.,Gun violence in the United States can result i...,
1347,Convert 20 inches to centimetres,,
1736,Calculate the sum of all the digits in the giv...,18047,
7723,Use the given data to create a bar chart,Region | Population\nNorth | 2000\nCent...,
9038,Convert the dates into ISO 8601 format,"November 25, 2020",
11263,Estimate the sum of (4^4+2^2+9),,
11355,Write a simple math equation to calculate 10% ...,,
11471,"Given a paragraph, summarize it in three sente...",The year 2020 has been an incredibly difficult...,
14634,Convert 20 minutes into seconds.,,
15015,"Given a passage, please output the number of w...","Every once in a while, it is important to reac...",
23488,Calculate 20% of 200.,,
24322,Calculate the area of the following shape in s...,rectangle of size 4 cm x 5 cm,
24449,Create a flow chart to explain the working of ...,,
24541,Generate a random example of an IPv4 address.,,
25034,"Given a set of shoe size, add up the total size","Size 4, Size 7, Size 9",
28250,Give the result of the following multiplication.,25 x 8,
30605,Create a movie poster for this movie.,Our Space Adventure,
31653,Convert 20 milliliters to tablespoons,,
32425,Determine the next two numbers in the followin...,,
35802,Construct a timeline to show the development o...,,
44274,"Given the following list of items, find their ...","2, 4, 6, 8",
45538,"What year was the movie ""La La Land"" released?",,
46258,Calculate the age of a person who was born on ...,No input,
46811,Compress the text to half of its original leng...,The year 2020 has been difficult for many peop...,
49181,Retrieve the following data from the World Ban...,,
49248,Make a projection of the expected income for t...,"Income in 2019: $50,000\nIncome increase rate ...",
51388,Generate an example of a bar chart to visually...,"Number of cats (2,5,3,1,4)",